### ISSUE TITLE
Simplify YAML driver_plugin

### ISSUE THREAD

**Issue by sethvargo** [jamie-ci/jamie#8]
I would like to propose a simpler syntax for the `driver_plugin` key:
1. Rename the key to "driver"
2. If the key is a string, then it's the driver plugin. If the key is a hash, then `[:plugin]` is the plugin and `[:x]`, `[:y]`, etc is the config

Examples: 

``` yaml
# Simplest, minimalistic example
driver: vagrant
```

``` yaml
# Custom configuration
driver:
  plugin: vagrant
  box: opscode-ubuntu-12.04
  box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
```
